apiVersion: v1
kind: Secret
metadata:
    name: linkding-user-auth
stringData:
    username: ENC[AES256_GCM,data:CDex59Gt,iv:c9PO9MCVNsbpbAE5aWL+klAJ3/dN1ZVe0MpSDo9rZB0=,tag:XdQjpWDoEQroR94/E4zwMg==,type:str]
    password: ENC[AES256_GCM,data:vtXH5niWUuQR,iv:o1++2Fok0zTNFrDEUiYSvxIxt06QxjHm2bnBdJdP64o=,tag:75gdHFZIKfEAe62n5k7KaA==,type:str]
sops:
    age:
        - recipient: age1lad6kkp37texcsurf9zgemy575yvyc3ms439ywh8jecud7zpj97q2eh2cf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWkVhcEYzZ0xMMDU0NFI3
            aFdhclY4YXBTK2hGall6Q3ArVnN6NXIxZTFRCjBUZENjZk9PcVdMS2dHbGpZYXZE
            eW9qWDNkTEdmOEFTTlp0THdQVGoza1UKLS0tIGpHdVpHTXh0cDg1S28xNDFKVzF1
            NDM0c2xyRURIYVExRmNqZFZBZ05pZzgKnCVlLiBqEGTKeVzszwAGyB9am5yLWAFg
            BJxC6sCePM0oPAquqd9Y3+dXZ0JRQ447svHK69ICrH6Z5da5kPbfZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T03:55:05Z"
    mac: ENC[AES256_GCM,data:oNkYWaszJKYSUUkVW7rMsBJisC837f1HLcYuLZFN4cCpeYCYZ61oRoT7ZvrDI08rUVdS0Nz0O40SWWUYiYXYIQj4GR35BouZNITUSrznXBk+k/Bp6QIYhnFO9ARF+30lQ3uSSOjZbxw4SnfLi69tcmp1MsGJme2K0HnpFbzTIkk=,iv:dKvi84Qg78udJK52QY7nBq1Jv+WXQO8ZYfTfXUzV9hk=,tag:wWaSnmbick7DetfVf4wmqA==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.11.0
